name: "Test Frontend (Node)"
description: "Run frontend tests using Node"
inputs:
  node_version:
    description: "Node version"
    required: false
    default: "20"
  working_directory:
    required: true
    description: "Working directory"

runs:
  using: "composite"
  steps:
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node_version }}
        cache: npm
        cache-dependency-path: ${{ inputs.working_directory }}/package-lock.json

    - name: Install deps
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: npm ci

    - name: Run tests
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: npm test
