name: "Test Backend (Maven)"
description: "Run backend tests using Maven"
inputs:
  java_version:
    description: "Java version"
    required: false
    default: "21"
  working_directory:
    required: true
    description: "Working directory"

runs:
  using: "composite"
  steps:
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ inputs.java_version }}
        cache: maven

    - name: Run Maven tests
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: mvn -q test
